import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';
import { formatUsdc, truncateKey } from '@/lib/utils';

/**
 * Formal proof of income statement.
 *
 * A downloadable document a bank, consulate, landlord, or tax office can read,
 * built on top of an on-chain income credential (feature F1). It states, in
 * plain language, that the recipient received income within a proven range over
 * a stated period, verified on the Stellar network, without revealing any exact
 * amount. Anyone can re-verify it independently through the QR code.
 *
 * The exact figure is intentionally absent: the proof attests range membership
 * only. The document never carries the employer private key, the nullifier
 * secret, or any randomness.
 */
export interface IncomeStatementData {
  companyName: string;
  companyCnpj: string;
  workerName: string;
  workerAddress: string;
  periodLabel: string; // e.g. "Tax year 2026" or "Jan 2026 to Jun 2026"
  range: { min: number; max: number }; // USDC dollars
  employerAx: string; // attesting employer key (full ax; truncated for display)
  credentialId: string;
  txHash: string;
  verifyUrl: string; // absolute /verify-income?n=&id= URL, encoded in the QR
  issuedAt: string; // ISO string
}

/**
 * Machine-readable form of the statement: the same facts the PDF shows, in a
 * clean JSON shape, for programmatic verification/ingestion. Mirrors
 * `receiptJson`. The exact amount is intentionally absent (same privacy
 * guarantee as the PDF: the proof attests range membership without the figure).
 */
export function incomeStatementJson(data: IncomeStatementData): Record<string, unknown> {
  return {
    status: 'verified_on_chain',
    document: 'proof_of_income',
    payer: { name: data.companyName, taxId: data.companyCnpj },
    recipient: { name: data.workerName, address: data.workerAddress },
    period: data.periodLabel,
    provenRange: { minUsdc: data.range.min, maxUsdc: data.range.max },
    attestingEmployerKey: data.employerAx,
    credentialId: data.credentialId,
    txHash: data.txHash,
    verifyUrl: data.verifyUrl,
    issuedAt: data.issuedAt,
  };
}

export async function generateIncomeStatementPdf(data: IncomeStatementData): Promise<Uint8Array> {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const qr = await QRCode.toDataURL(data.verifyUrl, { margin: 1, width: 220 });

  const left = 56;
  const right = 539;
  const valX = left + 150;
  let y = 64;

  // Header
  doc.setFont('helvetica', 'bold').setFontSize(22).setTextColor(15, 23, 42);
  doc.text('Proof of Income', left, y);
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(110);
  doc.text('Generated by ShieldPay, independently verifiable on the Stellar network', left, (y += 18));
  doc.setDrawColor(220).line(left, (y += 12), right, y);

  // Verified banner
  y += 26;
  doc.setFont('helvetica', 'bold').setFontSize(12).setTextColor(16, 185, 129);
  doc.text('STATUS: Proof of income verified on-chain', left, y);

  // Rows (full width; the QR sits below, so long values never collide with it).
  const row = (label: string, value: string) => {
    y += 22;
    doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(60).text(label, left, y);
    doc.setFont('helvetica', 'normal').setTextColor(20).text(value, valX, y);
  };
  // Monospace row for long values (address, tx hash): wraps within the page.
  const monoRow = (label: string, value: string) => {
    y += 22;
    doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(60).text(label, left, y);
    doc.setFont('courier', 'normal').setFontSize(8.5).setTextColor(20);
    const lines = doc.splitTextToSize(value, right - valX) as string[];
    doc.text(lines, valX, y);
    y += (lines.length - 1) * 10;
  };
  y += 6;
  row('Payer', data.companyName);
  row('Payer tax ID', data.companyCnpj);
  row('Recipient', data.workerName);
  monoRow('Recipient address', data.workerAddress);
  row('Period', data.periodLabel);
  row('Proven income', `${formatUsdc(data.range.min)} to ${formatUsdc(data.range.max)} USDC`);
  row('Attested by employer', truncateKey(data.employerAx, 8, 8));
  row('On-chain credential', `#${data.credentialId}`);
  monoRow('Verification tx', data.txHash);
  row('Issued at', new Date(data.issuedAt).toUTCString());

  // Plain-language statement (full width).
  y += 34;
  doc.setFont('helvetica', 'italic').setFontSize(10).setTextColor(80);
  const statement = doc.splitTextToSize(
    'This document is a proof of income, verified on the Stellar network, that the ' +
      'recipient named above received income within the stated range over the stated ' +
      'period. It was checked inside a Stellar smart contract; anyone can re-verify it ' +
      'independently by scanning the code below. The exact amounts are protected and ' +
      'are not disclosed by this proof, which attests only that the total falls within ' +
      'the range shown.',
    right - left,
  ) as string[];
  doc.text(statement, left, y);
  y += statement.length * 13;

  // QR + verify link (below the content, so nothing overlaps).
  y += 22;
  doc.addImage(qr, 'PNG', left, y, 110, 110);
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(110);
  doc.text('Scan to verify this proof of income.', left + 124, y + 56);
  doc.setFontSize(8).setTextColor(99, 102, 241);
  doc.textWithLink('Verify: ' + data.verifyUrl, left + 124, y + 74, { url: data.verifyUrl });

  // Footer
  doc.setFontSize(8).setTextColor(150);
  doc.text('ShieldPay · Confidential payroll on Stellar + Zero-Knowledge', left, 800);

  return new Uint8Array(doc.output('arraybuffer'));
}
