import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';
import { EXPLORER_BASE } from '@/lib/constants';

/**
 * Court-grade payment receipt ("Comprovante Judicial").
 *
 * This is document #5 of the legal defense chain (see docs/LEGAL.md). It binds,
 * in plain language a non-technical judge can read, the five pieces of proof:
 * contract, identity anchor, payment, on-chain ZK verification, and explorer link.
 */

export interface ReceiptData {
  companyName: string;
  companyCnpj: string;
  workerName: string;
  workerCpf: string;
  workerAddress: string;
  reference: string; // e.g. "May/2026"
  contractRange: { min: number; max: number };
  anchorTxHash: string;
  paymentTxHash: string;
  proofId: string;
  verifiedAtLedger: number;
}

export async function generateReceiptPdf(data: ReceiptData): Promise<Uint8Array> {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const verifyUrl = `${EXPLORER_BASE}/tx/${data.paymentTxHash}`;
  const qr = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 160 });

  let y = 56;
  const left = 56;

  doc.setFont('helvetica', 'bold').setFontSize(20);
  doc.text('Payment Proof', left, y);
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(110);
  doc.text('Generated by ShieldPay — verifiable on the Stellar network', left, (y += 18));

  doc.setTextColor(20).setFontSize(11);
  const row = (label: string, value: string) => {
    y += 22;
    doc.setFont('helvetica', 'bold').text(label, left, y);
    doc.setFont('helvetica', 'normal').text(value, left + 150, y);
  };

  y += 14;
  row('Payer', `${data.companyName} (CNPJ ${data.companyCnpj})`);
  row('Recipient', `${data.workerName} (CPF ${data.workerCpf})`);
  row('Stellar address', data.workerAddress);
  row('Reference', data.reference);
  row('Contractual range', `$${data.contractRange.min} – $${data.contractRange.max} USDC`);
  row('Identity anchor tx', data.anchorTxHash);
  row('Payment tx', data.paymentTxHash);
  row('On-chain proof id', data.proofId);
  row('Verified at ledger', String(data.verifiedAtLedger));
  row('Status', 'Mathematically verified on-chain');

  // Plain-language statement for the court.
  y += 40;
  doc.setFont('helvetica', 'italic').setFontSize(10).setTextColor(80);
  const statement = doc.splitTextToSize(
    'This document is a mathematical proof, generated by the Stellar blockchain, ' +
      'that the amount was deposited to the recipient address within the agreed ' +
      'contractual range at the ledger shown above. The verification code can be ' +
      `validated at ${verifyUrl}.`,
    430,
  );
  doc.text(statement, left, y);

  // QR code to the explorer.
  doc.addImage(qr, 'PNG', 380, 96, 120, 120);
  doc.setFontSize(8).setTextColor(110).text('Scan to verify', 410, 226);

  return new Uint8Array(doc.output('arraybuffer'));
}
