import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';

/**
 * Verifiable payment receipt.
 *
 * Binds, in plain language a non-technical reader (auditor, accountant) can
 * read, the proof trail: payer, recipient, reference, the proven contractual
 * range, the on-chain zero-knowledge proof id, the Stellar transaction that
 * verified it, and a QR code to independently re-verify on the public explorer.
 *
 * The exact amount is intentionally absent — the proof attests range membership
 * without disclosing the figure (revealed only under a viewing key).
 */
export interface ReceiptData {
  companyName: string;
  companyCnpj: string;
  workerName: string;
  workerAddress: string;
  reference: string;
  range: { min: number; max: number }; // USDC dollars
  proofId: string;
  txHash: string;
  explorerUrl: string;
  issuedAt: string; // ISO string
}

export async function generateReceiptPdf(data: ReceiptData): Promise<Uint8Array> {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const qr = await QRCode.toDataURL(data.explorerUrl, { margin: 1, width: 220 });

  const left = 56;
  let y = 64;

  // Header
  doc.setFont('helvetica', 'bold').setFontSize(22).setTextColor(15, 23, 42);
  doc.text('Payment Proof', left, y);
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(110);
  doc.text('Generated by ShieldPay — independently verifiable on the Stellar network', left, (y += 18));
  doc.setDrawColor(220).line(left, (y += 12), 539, y);

  // Verified banner
  y += 26;
  doc.setFont('helvetica', 'bold').setFontSize(12).setTextColor(16, 185, 129);
  doc.text('STATUS: Mathematically verified on-chain', left, y);

  // Rows
  doc.setFontSize(11);
  const row = (label: string, value: string) => {
    y += 24;
    doc.setFont('helvetica', 'bold').setTextColor(60).text(label, left, y);
    doc.setFont('helvetica', 'normal').setTextColor(20).text(value, left + 160, y);
  };
  y += 6;
  row('Payer', `${data.companyName}`);
  row('Payer CNPJ', data.companyCnpj);
  row('Recipient', data.workerName);
  row('Recipient address', data.workerAddress);
  row('Reference', data.reference);
  row('Proven range', `$${data.range.min} - $${data.range.max} USDC`);
  row('On-chain proof id', `#${data.proofId}`);
  row('Verification tx', data.txHash);
  row('Issued at', new Date(data.issuedAt).toUTCString());

  // Plain-language statement
  y += 40;
  doc.setFont('helvetica', 'italic').setFontSize(10).setTextColor(80);
  const statement = doc.splitTextToSize(
    'This document is a mathematical proof, generated and verified by the Stellar ' +
      'blockchain, that a payment to the recipient address above falls within the ' +
      'agreed contractual range. The proof was checked inside a Stellar smart ' +
      'contract; anyone can re-verify it independently using the transaction below. ' +
      'The exact amount is protected and is not disclosed by this proof.',
    430,
  );
  doc.text(statement, left, y);

  // QR + link
  doc.addImage(qr, 'PNG', 380, 150, 130, 130);
  doc.setFontSize(8).setTextColor(110).text('Scan to verify on-chain', 405, 290);
  y += 90;
  doc.setFontSize(8).setTextColor(99, 102, 241);
  doc.textWithLink('Verify: ' + data.explorerUrl, left, y, { url: data.explorerUrl });

  // Footer
  doc.setFontSize(8).setTextColor(150);
  doc.text('ShieldPay · Payroll & Payment Proof on Stellar + Zero-Knowledge', left, 800);

  return new Uint8Array(doc.output('arraybuffer'));
}
